### PR TITLE
Fix doc build by using local video

### PR DESCRIPTION
**Pull request by scotts**
We've been hitting a 403 in our docs build. That is not initially why we opened Issue #203, but it does seem to be the current problem. Building the docs in CI and locally hits a 403 on the video. Rather than trying to debug that, I think it's easier and more robust to always use a local version of the video.

### CODE REVIEW

**Review by NicolasHug — COMMENTED** [review]
I think we need to be mindful of the repo's size. We're already storing a bunch of videos for testing and adding a new one just for docs may not be necessary.

Over time and with more history, repos can become extremely large (x GBs), and that can create friction. Should we just try to find another video?

**Comment by scotts** [comment]
@NicolasHug, I understand your concern. In this case, I think it's worth it.

The problem I encountered was that the video _is_ available. I can download it locally on my Mac and my devserver through `wget`. It was just failing (getting a 403) during the doc build, both in CI and on my devserver. There's probably something about the environment of the sphinx build that, somehow, is not okay with doing a download. So I don't think we can quickly fix this problem by using a different video - I believe the root problem is that we're trying to grab a video from the internet. I'm afraid that figuring out why we can't download something during our sphinx build will require a deep investigation.

I also think it's not great that our docs build is non-determistic. I think it leads to these kinds of problems, and I'm worried we'll constantly play whack-a-mole trying to keep them healthy.

**Comment by NicolasHug** [comment]
I'll give this a look next week, but I don't think we should vendor the video in the repo. This forces users to manually download the video locally to run the example, and prevents them from running this example on colab. That's not a pleasant or convenient first experience with torchcodec, so I think it's important to address with care.

**Comment by scotts** [comment]
@NicolasHug, if you think you can keep the docs build robust while still downloading a video, that's great! I'm going to continue using this draft PR to see if I can fix the original reason we opened #203. Now that we're no longer getting a 403, I can see that the CI is failing with the same problem as before.

**Comment by scotts** [comment]
@NicolasHug, note that I changed the PyTorch install to also include `torchvision` and `torchaudio`. That is, I copied it exactly from https://pytorch.org/get-started/locally/. That seemed to make the problem go away. If you can pair that change with your future fix, we should be able to get the docs building in CI again.

**Comment by scotts** [comment]
Abandoning in favor of @NicolasHug's fix in #217.

**Pull request closed without merging**
